# Generated by Django 3.2.8 on 2021-11-10 21:57

import apps.complaints.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintId', models.CharField(default=apps.complaints.models.Complaint.abrIdGenerator, editable=False, max_length=36)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('receivedBy', models.CharField(choices=[('CS', 'Customer Service'), ('QA', 'Quality Assurance'), ('SE', 'Security')], default='Customer Service', max_length=24, verbose_name='Received By')),
                ('complainant', models.CharField(choices=[('Customer', 'Customer'), ('Doctor', 'Doctor'), ('Hospital', 'Hospital'), ('Regulatory', 'Regulatory')], default='Customer', max_length=24, verbose_name='Complainant')),
                ('complaintType', models.CharField(choices=[('select', 'select'), ('Quality', 'Quality'), ('Packaging', 'Packaging'), ('Shipping', 'Shipping'), ('Wrong Order', 'Wrong Order'), ('Defective', 'Defective'), ('Loss/Theft', 'Loss/Theft'), ('Adverse Rx', 'Adverse Reaction'), ('Serious Adx', 'Serious Adverse Reaction')], default='complaint type', max_length=32, verbose_name='Complaint Type')),
                ('description', models.TextField(verbose_name='Complaint Description')),
                ('contactVia', models.CharField(choices=[('select', 'select'), ('Email', 'Email'), ('Phone', 'Phone'), ('Fax', 'Fax')], default=None, max_length=32, verbose_name='Contact')),
                ('confirmation', models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed')], default='Not Confirm', max_length=42, verbose_name='Complaint is')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('investigationTitle', models.CharField(max_length=256, verbose_name='Title')),
                ('investigation', models.TextField(blank=True, max_length=3000, verbose_name='Quality Investigation')),
                ('conclusion', models.TextField(max_length=2000, verbose_name='Conclusions')),
                ('correctAction', models.TextField(max_length=2000, verbose_name='Corrective Actions')),
                ('capa', models.CharField(max_length=250, verbose_name='CAPA')),
                ('qualityInstanceId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('incidentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=24, verbose_name='Product Name')),
                ('productLot', models.CharField(max_length=24, verbose_name='Lot #')),
                ('NumOfUnits', models.IntegerField(default=1, verbose_name='Units #')),
                ('weight', models.FloatField(default=0.0, help_text='in grams or ml', max_length=24, verbose_name='Weight')),
                ('productType', models.CharField(choices=[('select', 'select'), ('Dry Flower', 'Dry Flower'), ('Pre-Rolls', 'Pre-Rolls'), ('Extracts', 'Extracts'), ('Oil', 'Oil'), ('Vape', 'Vape Cartridge'), ('Battery', 'Battery')], default=None, max_length=24, verbose_name='Product Type')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('firstName', models.CharField(max_length=24, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=24, verbose_name='Last Name')),
                ('identificatioId', models.CharField(max_length=24, verbose_name='Identification ID')),
                ('address', models.TextField(default=None, max_length=64, verbose_name='Address')),
                ('zipcode', models.CharField(default=None, max_length=7, verbose_name='Postal Code')),
                ('province', models.CharField(choices=[('select', 'select'), ('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('SK', 'SK'), ('YK', 'YK'), ('ON', 'ON'), ('QC', 'QC'), ('NB', 'NB'), ('NS', 'NS'), ('NF', 'NF')], default=None, max_length=12, verbose_name='Province')),
                ('customerInstanceId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
    ]
