# Generated by Django 4.0 on 2022-02-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
