# Generated by Django 4.0 on 2022-02-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesTechnicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='covers/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.IntegerField(blank=True)),
            ],
        ),
    ]
