# Generated by Django 4.0 on 2022-02-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comments_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='news.news'),
        ),
    ]
